CREATE TABLE players (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  age INT NOT NULL,
  country VARCHAR(100) NOT NULL,
  position VARCHAR(100) NOT NULL,
  image VARCHAR(255) NOT NULL,
  number INT NOT NULL,
  seasons INT NOT NULL
);
